// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjbPzvVYwmNN4L3l0jA6D1XipxMUQXlQ0',
    appId: '1:726004977188:android:fe2a96f5cd6222844e92b1',
    messagingSenderId: '726004977188',
    projectId: 'true-protection-th',
    storageBucket: 'true-protection-th.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDFT-KwEbZsL3ZQRyrVJ-8PS_zHvDy2c',
    appId: '1:726004977188:ios:2d1b345e489eb76e4e92b1',
    messagingSenderId: '726004977188',
    projectId: 'true-protection-th',
    storageBucket: 'true-protection-th.appspot.com',
    iosClientId: '726004977188-deuhlu8t631r1gmhdar368a5ccv2hghf.apps.googleusercontent.com',
    iosBundleId: 'com.tureprotection.customer',
  );
}
